### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by donlucacorleone** [webtiming/timingsrc#2]
Hi,
I read across all your awesome project looking for the right way of how to handle a video loop.

Let's take this as an example:
videoA is a background looping video, with a duration of 10 seconds, but looping forever.
videoB is another video with a duration of 2 minutes.

I'd like to sync-play them, using your mediaSync library (e.g. at seconds 40 videoA and videoB are still playing).

Since the timeline is only one, shared between these 2 videos, what do I need to correctly loop the videoA while still playing videoB? I can't reset the timeline, otherwise I reset the videoB too.

How can I sync these video across multiple devices?
In general, how do I handle video loops?

Thanks

**Comment by donlucacorleone** [comment]
Oopsie, totally missed! Thank you for pointing that out.

I made an example: http://jsfiddle.net/Lwxbdt1r/
(to correctly view it, go to Settings -> Bottom results)

Video on the right is a 32 seconds loopable video.
Video on the left is the same video concatenated with ffmpeg in order to make it lasts 2 hours or so.

As you can see, when loop occured, the video on the right did stutter a bit; that is, it's not a seamless loop.
By the way, your timing object did the job and in few seconds it "aligned" the right video to the correct one (the left one). And that's fantastic!

I think this is a problem related to codec, or the seek to 0 needed to actually do the loop, or the 60fps...
Have you ever encountered a similar behaviour?

FYI video on the right has these info (got from mediainfo):
```
General
Complete name                            : barra-360-2.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 150 KiB
Duration                                 : 32 s 0 ms
Overall bit rate                         : 38.4 kb/s
Writing application                      : Lavf57.83.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 32 s 0 ms
Bit rate                                 : 36.2 kb/s
Width                                    : 640 pixels
Height                                   : 360 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 60.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.003
Stream size                              : 141 KiB (94%)
Writing library                          : x264 core 152 r2854 e9a5903
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=3 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
```

**Comment by ingararntzen** [comment]
Hi again.

That's a fine demo :)

You are quite right, looping with the timingobject is not seamless - as it involves skipping the video player for every loop. It's pretty close to seamless though, so for many applications the difference is mostly of academic interest perhaps. On the other hand, it is a pretty practical way of doing stuff - and it provides a valuable alternative to actually manipulating video assets. Note that you can similarly use the RangeConverter to make a non-looping video clip from a random video, without actually clipping the video and making it available as new media asset. That's pretty sweet.

With respect to the intermittently visible differences. I'm not entirely sure what their cause are. I suspect this particular demo makes it easy to spot very small errors. As mentioned, every skip poses an extra challenge for the mediasync library to "resync" it. At any point in time, the other video may also be slightly out of sync. We've also had issues before with using video.duration as source of loop interval, because this value is not guaranteed to be the same across browsers. And then there are all the possible sources you mention with video decoding and stuff.

My colleague Njål Borch (@Snarkdoof) perhaps has more insight here.

**Comment by donlucacorleone** [comment]
Hi and thank you for your reply.

If you use this demo with two identical non-looping videos, they are perfectly sync 99% of time! I mean, frame-sync!
And, as you noted, this is a very particular video made especially for these type of tests.
So, again, congratulations for your idea and the awesome library.

Will wait for kindly message from Njål.

Luca

**Comment by Snarkdoof** [comment]
Very cool demonstration, I used it to improve the media sync library a bit
- it's not really been tuned for 60fps video, but now it handles it a bit
better.  We do still have issues with Chrome in particular due to a very
coarse reporting of currentTime, Firefox does seem to be the better browser
for tight sync these days (also on Android) (your loop points are much more
visible, but it corrects it better).

And the video you have doesn't autoplay on Chrome, but as it doesn't have
audio you can set "muted=true" on the video element, and it should auto
play for all.

Keep up the good work
N

**Comment by donlucacorleone** [comment]
It took me some time to get it works like a charm but finally I think I'm very close to the solution: a seamless loop sync'ed using TimingObject!

Firstly, let's see it in action: [http://jsfiddle.net/pLsmwto5/8/](http://jsfiddle.net/pLsmwto5/8/)

Now it's time for the boring explanation 😄 :
Seamless loop alone works well in Chromium (didn't test any other browser).
But when you introduce the Timing Object controller (especially the LoopConverter), it dropped some frames (see my previous post).
Reading the web, I came across the Media Source Extension [https://w3c.github.io/media-source/](https://w3c.github.io/media-source/) and in particular this example: [https://developers.google.com/web/fundamentals/media/mse/seamless-playback](https://developers.google.com/web/fundamentals/media/mse/seamless-playback)
So, putting them together, I finally found how to accomplish this task.


Njål and Ingar, I'd like to share this solution and the relevant code in order to let you test & improve Timing Object if needed. Infact I saw that sometimes the 3 videos are delayed by 1 frame (no more indeed), although they went perfectly re-synced at some point 👍 .
As you pointed out, this is a really bastard demo: 3 videos, 60fps, and it's easy to notice any slight delay.

Please let me know if I can help you further more.
Thank you for your attention.
Luca

**Comment by Snarkdoof** [comment]
Hi Luca, and that's a pretty sweet way to solve it! :-) I actually did make
a thing that needed to loop videos, but I ignored the minor issues. I also
did some work with media source extensions, but not for looping, so there
you go. :-)

And I find that the demo works incredibly well in Firefox, they're always
on the same frame!

Thanks again for a very cool demo, would you be fine with me copying it and
making it a test page on our examples server? Would be gold to check
consistency within various browsers.

N

**Comment by donlucacorleone** [comment]
Yes of course!
Infact I run Chromium (dev) 72.0.3590.0 on an Ubuntu 18.04 Intel NUC and, every now and then, I saw a small delay (1 frame) 🤔
