### ISSUE TITLE
Sequencer usage and issues.

### ISSUE THREAD

**Issue by CristianoSoleti** [webtiming/timingsrc#6]
Hello,
Can sequencer be used for live streaming?
Right now i'm trying my rough implementation of it, but the callbacks for seq.on('change') are not triggered.
Although everything else is "working fine" as in, not getting any errors.
Any suggestion about that?

**Comment by ingararntzen** [comment]
Yes - you can add cues to the sequencer at any time.

```js
s.addCue("mykey", new Interval(42, 44), "mydata");
```

The change event will fire if the following two conditions are met, so make sure to check that.
- you have added a cue with an interval, say `[a,b>`
- the position `p` of the timing object (to.query().position) is somewhere between a and b.

If you have tied your cue to a singular value
```js
s.addCue("mykey", new Interval(42), "mydata");
```
The change event will fire only i the position `p` of the timing object is exactly 42, or if timing object plays passed 42 with some velocity.

**Comment by CristianoSoleti** [comment]
Alright , the callbacks are now triggered, thanks.
Altho this means, that everyone can add something at the sequencer? As in, someone can actually hack it and let other people get what he wants? Or sort of..

**Comment by ingararntzen** [comment]
The sequencer is not a data distribution mechanism. So no.

The sequencer is just a fancy delay/buffering-mechanism which you insert into your web page - to decouple receipt of data from presentation of data. As such, tampering with cues in the sequencer will only have local effects on that web page. If you use the sequencer for updating the DOM, tampering with the sequencer would be equivalent in effect to tampering with the DOM.

Adding delay to presentation does not change much with respect to security - except in the trivial sense that any kind of delay will give an adversary more time to do malice. 

Typically you would want to encapsulate the sequencer in your app code (just like you encapsulate your incoming data stream) so that it is not available as a global variable in the web page.

**Comment by CristianoSoleti** [comment]
Alirght i got it. Thanks for the support

**Comment by CristianoSoleti** [comment]
Actually, sorry but I got another issue, i call the addCue in 2 different points of my code (one for previous fetched stuff, and another one for on going stuff), apparently the first one is ignored, and the second one is working fine, and i'm pretty sure i'm doing things right.  As in , according to my logs, something should have happened.
Am I missing something?

**Comment by ingararntzen** [comment]
Please provide a minimal code snippet involving two cues, one timing object and one sequencer object where you demonstrate your issue.

**Comment by CristianoSoleti** [comment]
Ok i found the issue. The key was undefined for some reason, my bad.

Basically if the key of the addCue function is undefined, it won't create the cue ( which makes sense, my bad)
