### ISSUE TITLE
Can't override native video controls?

### ISSUE THREAD

**Issue by domeav** [webtiming/timingsrc#9]
Hello,

I'm tinkering with the MediaSync demo, attempting to use the first player native controls, but the pause behaves strangely : it does not stop the playback but makes it choppy and I can't understand what I'm doing wrong. Is this a bug?

Here is my code: http://larallonge.franceimpro.net/static/timingsrc/test.html

Thanks for your work!

**Comment by ingararntzen** [comment]
Hi. Yeah, you need to intercept and re-route the native controls, so that for instance the click event from the pause button does not affect the video at all, but instead is applied to the timing object. Keep in mind that the mediasync wrapper is trying to control the video according to the state of the timing object at any time, so if you apply control directly on the video, this effectively means you are introducing synchronization errors which the the mediasync wrapper then needs to correct as soon as it can - this accounts for the behavior you describe. If you instead communicate control signal via the timing object, all there wont be a conflict.

**Comment by ingararntzen** [comment]
Also, there is the option of disabling the native controls, and instead create your own controls, which can then be used even without the video.

**Comment by Snarkdoof** [comment]
To clearify, the mediasync object overrides the internal video controls, so
you have to create your own and connect it to the timing object (e.g. set
velocity to 0 as opposed to run pause() on the video element).

The reason is that the video controls control the internal clock of the
video player while a timing object is an external clock that the video
slaves after.

Best regards
N

**Comment by domeav** [comment]
Thank you very much to both of you for your insight! I'll create my own controls then.

**Comment by abdulzeedo** [comment]
> Hi. Yeah, you need to intercept and re-route the native controls, so that for instance the click event from the pause button does not affect the video at all, but instead is applied to the timing object. Keep in mind that the mediasync wrapper is trying to control the video according to the state of the timing object at any time, so if you apply control directly on the video, this effectively means you are introducing synchronization errors which the the mediasync wrapper then needs to correct as soon as it can - this accounts for the behavior you describe. If you instead communicate control signal via the timing object, all there wont be a conflict.

I am trying to somehow get control of the seek functionality using native controls (for reasons, I cannot use customized controls). How would you implement it?

**Comment by ingararntzen** [comment]
Haven't done this myself, but you would need to follow the same pattern: Intercept and handle the event that is generated when user clicks on the progress bar -- before it has taken effect (perhaps mousedown or something), get the requested media offset from the event and use it to update the position of the timingobject.

**Comment by Snarkdoof** [comment]
As far as I know, there is no way of doing this with native controls as you
will get events from the media element, not the controls. You will have to
monitor the media element for skips. Customized controls are normally
possible though, so perhaps you should look into that again.

N
